#!/usr/bin/env bash
# Regenerates the reference oracle from the pinned submodule.
#
# The recipes are spread across two makefiles with the option lists fighting
# each other, so they are written down here once. Two of them are load-bearing
# beyond their content:
#
#   - `-norm1` and `-norm2` are the only way to reach the `.sig` and `.type`
#     dumps, and `-norm2` is undocumented: `--help` lists `-norm` and `-norm1`
#     then skips on (`global.cpp:2559-2566`) though it parses (`:1504-1512`).
#   - `-I dsp` is on every level, where the reference makefile puts it on four
#     of five. The `.ir` rules look like they rely on `fopenSearch` pushing
#     `dsp/` onto the importing file's own directory; measured, that loses to the
#     machine's installed library directory, so without the flag every level
#     resolves against whatever Faust happens to be installed. `-e` with no
#     `-I` takes `music.lib` from /usr/local and drops `APF.box` from 91 of 93
#     matching the shipped set to zero. The reference makefile passes the flag
#     through `FAUSTOPTIONS`, which is one variable and so drops `-double` in
#     the process; passing both is the whole reason this script exists.
#
# The shipped structural files are `-single` while `.ir` is `-double`, so
# everything here is regenerated at our own `-double` rather than compared as
# shipped. Regenerate rather than trust: the `faust` on a developer's PATH is
# not the submodule's, and the checked-in files were generated by 2.81.0.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
faust=$root/lib/faust/build/bin/faust
impulse=$root/lib/faust/tests/impulse-tests
out=${FAUSTLENS_ORACLE_DIR:-$root/build/oracle}
levels=${1:-structural}   # structural | ir | all | compare

if [[ ! -x $faust ]]; then
    cat >&2 <<EOF
Reference Faust is not built. From $root/lib/faust/build:
    cmake -C backends/regular.cmake -DFIR_BACKEND=COMPILER -B faustdir -G Ninja .
    ninja -C faustdir faust
\`regular.cmake\` is the preset that avoids LLVM, but it sets FIR_BACKEND OFF
and \`.fir\` needs \`-lang fir\`; no shipped preset gives FIR without LLVM.
EOF
    exit 1
fi

sha=$(git -C "$root/lib/faust/libraries" rev-parse HEAD)
echo "faust:          $("$faust" --version | head -1)"
echo "faustlibraries: $sha"
echo "output:         $out"
mkdir -p "$out"
echo "$sha" > "$out/faustlibraries.sha"

cd "$impulse"

structural() {
    for dsp in dsp/*.dsp; do
        name=$(basename "$dsp" .dsp)
        # Failures are recorded rather than fatal: a handful of programs in the
        # corpus have no output at some levels, and the shipped set is short of
        # 94 at every one of them.
        "$faust" -double -I dsp -e "$dsp" -o "$out/$name.box"     2>>"$out/errors.log" || true
        "$faust" -double -I dsp -norm1 "$dsp" > "$out/$name.sig"  2>>"$out/errors.log" || true
        FAUST_OPT=FAUST_SIG_NO_NORM \
        "$faust" -double -I dsp -norm1 "$dsp" > "$out/$name.nonorm.sig" \
            2>>"$out/errors.log" || true
        "$faust" -double -I dsp -norm2 "$dsp" > "$out/$name.type" 2>>"$out/errors.log" || true
        "$faust" -lang fir -double -I dsp "$dsp" > "$out/$name.fir" \
            2>>"$out/errors.log" || true
        printf .
    done
    echo
    find "$out" -size 0 -delete
}

# The `.ir` files are a protocol, not just a buffer of numbers: four
# concatenated sections of 15000 frames, 44100 Hz, blocks of 64, an impulse on
# every input in the first block with all buttons held at 1.
impulse_responses() {
    mkdir -p "$out/ir" "$out/cpp"
    for dsp in dsp/*.dsp; do
        name=$(basename "$dsp" .dsp)
        "$faust" -double -I dsp -i -a archs/impulsearch.cpp "$dsp" -o "$out/cpp/$name.cpp" \
            2>>"$out/errors.log" || { printf x; continue; }
        c++ -O3 -I"$root/lib/faust/architecture" -Iarchs -pthread -std=c++11 \
            "$out/cpp/$name.cpp" -o "$out/cpp/$name" 2>>"$out/errors.log" || { printf x; continue; }
        "$out/cpp/$name" -n 60000 > "$out/ir/$name.ir" 2>>"$out/errors.log" || printf x
        printf .
    done
    echo
}

# `filesCompare` is standalone C++ and links nothing
# (`tests/impulse-tests/Makefile:553-554`), so the oracle never builds libfaust.
# Its three arguments are positional -- test, reference, tolerance -- while
# `-part` is found by scanning argv, so `-part` must come *after* them or it
# displaces the test file and the tolerance is read from a filename.
tools() {
    c++ -O3 -std=c++11 tools/filesCompare.cpp -o "$out/filesCompare"
}

# A *provenance* check -- did we regenerate against the right libraries at the
# right precision -- and not the conformance suite's isomorphism checks, which
# compare graphs and multisets. The shipped structural files are `-single` and
# these are `-double`, so this drops the compiler-generated header lines and
# masks numeric literals; what is left is the graph, which precision must not
# change.
#
# `.fir` is left out deliberately. It is compared as a projection -- the set of
# state fields with their shapes, and which band each computation landed in --
# and textually it differs from the shipped `-single` dump in one further way
# the mask cannot reach without hiding real differences: at single precision the
# compiler emits the `f`-suffixed libm names, `sinf` and `max_f` against `sin`
# and `max_`. Masking that would obscure exactly the kind of difference the
# projection looks for, and the three levels below already answer the provenance
# question.
compare() {
    local ok=0 differ=0 absent=0
    for ext in box sig type; do
        ok=0; differ=0; absent=0
        for f in "$out"/*."$ext"; do
            [ -e "$f" ] || continue
            local name; name=$(basename "$f")
            case $name in *.nonorm.sig) continue ;; esac
            local shipped=reference/$name
            if [ ! -f "$shipped" ]; then absent=$((absent + 1)); continue; fi
            if diff -q <(normalize "$f") <(normalize "$shipped") > /dev/null; then
                ok=$((ok + 1))
            else
                differ=$((differ + 1))
                [ -n "${VERBOSE:-}" ] && echo "    differs: $name"
            fi
        done
        printf '  %-5s %3d match, %d differ, %d without a shipped file
'             ".$ext" "$ok" "$differ" "$absent"
    done
    echo "  .fir  skipped -- compared as a projection by the conformance suite"
    if [ -d "$out/ir" ]; then
        ok=0; differ=0; absent=0
        for f in "$out"/ir/*.ir; do
            [ -e "$f" ] || continue
            local shipped=reference/$(basename "$f")
            if [ ! -f "$shipped" ]; then absent=$((absent + 1)); continue; fi
            if "$out/filesCompare" "$f" "$shipped" 2e-06 > /dev/null 2>&1; then
                ok=$((ok + 1))
            else
                differ=$((differ + 1))
                [ -n "${VERBOSE:-}" ] && echo "    differs: $(basename "$f")"
            fi
        done
        printf '  %-5s %3d match, %d differ, %d without a shipped file
'             ".ir" "$ok" "$differ" "$absent"
    fi
}

normalize() {
    grep -v 'declare version\|compile_options\|library_path\|declare filename' "$1" \
      | sed -E 's/[0-9]+\.[0-9]*([eE][-+]?[0-9]+)?f?/N/g; s/[0-9]+[eE][-+]?[0-9]+f?/N/g'
}

: > "$out/errors.log"
case $levels in
    structural) tools; structural ;;
    ir)         tools; impulse_responses ;;
    all)        tools; structural; impulse_responses ;;
    compare)    echo "against the shipped set:"; compare; exit 0 ;;
    *) echo "usage: $0 [structural|ir|all|compare]" >&2; exit 2 ;;
esac

echo "regenerated:"
for ext in box sig type fir; do
    printf '  %-6s %3d (shipped %d)\n' ".$ext" \
        "$(find "$out" -maxdepth 1 -name "*.$ext" ! -name '*.nonorm.sig' | wc -l | tr -d ' ')" \
        "$(find reference -maxdepth 1 -name "*.$ext" | wc -l | tr -d ' ')"
done
[[ -d $out/ir ]] && printf '  %-6s %3d\n' ".ir" "$(find "$out/ir" -name '*.ir' | wc -l | tr -d ' ')"
[[ -s $out/errors.log ]] && echo "  (diagnostics in $out/errors.log)"
exit 0
