// Generated by cmake/EmbedStdlib.cmake with paths relative to faustlibraries.
#pragma once

#include <span>
#include <string_view>

namespace faustlens {

struct StdlibEntry {
    std::string_view Path;
    std::string_view Text;
};

std::span<const StdlibEntry> EmbeddedStdlib();

// The oracle must use this faustlibraries revision.
const char *EmbeddedStdlibSha();

} // namespace faustlens
