// The embedded standard library, generated by `cmake/EmbedStdlib.cmake` and
// keyed by path relative to the `faustlibraries` checkout.
#pragma once

#include <span>
#include <string_view>

namespace faustlens {

struct StdlibEntry {
    std::string_view Path;
    std::string_view Text;
};

std::span<const StdlibEntry> EmbeddedStdlib();

// The `faustlibraries` commit the bytes came from. An oracle is comparable only
// if generated against the same one.
const char *EmbeddedStdlibSha();

} // namespace faustlens
